import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const rubik = localFont({
  src: [
    {
      path: "fonts/rubik/Rubik-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-rubik",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={` ${rubik.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
